name: Sonar

on:
  - push
  - pull_request

jobs:
  sonarqube:
    name: SonarQube Cloud
    runs-on: ubuntu-latest
    services:
      app:
        image: hexletprojects/qa_auto_python_testing_kanban_board_project_ru_app
        ports:
          - 5173:5173
        options: >-
          --health-cmd="curl -f http://localhost:5173/ || exit 1"
          --health-interval=2s
          --health-timeout=5s
          --health-retries=10
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - name: Install uv and dependencies
        run: |
          pip install uv
          uv sync --group dev
      - name: Run tests to generate coverage report
        run: |
          uv run pytest --cov=gendiff --cov-report=xml
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
